-- =====================================================
-- 1. БАЗОВЫЕ ТАБЛИЦЫ
-- =====================================================

-- Таблица рейтингов MPA
CREATE TABLE IF NOT EXISTS mpa (
    id INTEGER PRIMARY KEY,
    name VARCHAR(10) NOT NULL
);

-- Таблица жанров
CREATE TABLE IF NOT EXISTS genres (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(100) NOT NULL,
    name VARCHAR(100),
    birthday DATE
);

-- Уникальные ограничения для users
ALTER TABLE users ADD CONSTRAINT IF NOT EXISTS uk_users_email UNIQUE (email);
ALTER TABLE users ADD CONSTRAINT IF NOT EXISTS uk_users_login UNIQUE (login);

-- Таблица фильмов
CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE,
    duration INTEGER,
    mpa_id INTEGER REFERENCES mpa(id)
);

-- Таблица связи фильмов и жанров
CREATE TABLE IF NOT EXISTS film_genre (
    film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genres(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    PRIMARY KEY (film_id, genre_id)
);

-- Таблица дружбы
CREATE TABLE IF NOT EXISTS friendship (
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    friend_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id)
);

-- =====================================================
-- 2. ТАБЛИЦА ОЦЕНОК (вместо likes)
-- =====================================================

CREATE TABLE IF NOT EXISTS marks (
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    mark_value INTEGER NOT NULL CHECK (mark_value BETWEEN 1 AND 10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (film_id, user_id),
    FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =====================================================
-- 3. ФУНКЦИОНАЛЬНОСТЬ «ОТЗЫВЫ» (Reviews)
-- =====================================================

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(1000) NOT NULL,
    is_positive BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,
    useful INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review_ratings (
    review_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    is_like BOOLEAN NOT NULL,
    PRIMARY KEY (review_id, user_id),
    FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =====================================================
-- 4. ФУНКЦИОНАЛЬНОСТЬ «РЕЖИССЁРЫ» (Directors)
-- =====================================================

CREATE TABLE IF NOT EXISTS directors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film_director (
    film_id BIGINT NOT NULL,
    director_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, director_id),
    FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    FOREIGN KEY (director_id) REFERENCES directors(id) ON DELETE CASCADE
);

-- =====================================================
-- 5. ФУНКЦИОНАЛЬНОСТЬ «ЛЕНТА СОБЫТИЙ» (Feed)
-- =====================================================

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    event_type VARCHAR(20) NOT NULL,   -- LIKE, REVIEW, FRIEND, MARK
    operation VARCHAR(20) NOT NULL,    -- REMOVE, ADD, UPDATE
    entity_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =====================================================
-- 6. БАЗОВЫЕ ИНДЕКСЫ
-- =====================================================

-- Индексы для users
CREATE INDEX IF NOT EXISTS idx_users_login ON users(login);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- Индексы для films
CREATE INDEX IF NOT EXISTS idx_films_release_date ON films(release_date);
CREATE INDEX IF NOT EXISTS idx_films_mpa_id ON films(mpa_id);
CREATE INDEX IF NOT EXISTS idx_films_name ON films(name);

-- Индексы для film_genre
CREATE INDEX IF NOT EXISTS idx_film_genre_film_id ON film_genre(film_id);
CREATE INDEX IF NOT EXISTS idx_film_genre_genre_id ON film_genre(genre_id);

-- Индексы для friendship
CREATE INDEX IF NOT EXISTS idx_friendship_user_id ON friendship(user_id);
CREATE INDEX IF NOT EXISTS idx_friendship_friend_id ON friendship(friend_id);

-- =====================================================
-- 7. ИНДЕКСЫ ДЛЯ ОЦЕНОК (marks)
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_marks_film_id ON marks(film_id);
CREATE INDEX IF NOT EXISTS idx_marks_user_id ON marks(user_id);
CREATE INDEX IF NOT EXISTS idx_marks_value ON marks(mark_value);
CREATE INDEX IF NOT EXISTS idx_marks_film_user ON marks(film_id, user_id);

-- Индекс для быстрого вычисления средней оценки
CREATE INDEX IF NOT EXISTS idx_marks_avg ON marks(film_id, mark_value);

-- =====================================================
-- 8. ИНДЕКСЫ ДЛЯ ОТЗЫВОВ
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_film_id ON reviews(film_id);
CREATE INDEX IF NOT EXISTS idx_reviews_useful ON reviews(useful DESC);

CREATE INDEX IF NOT EXISTS idx_review_ratings_review_id ON review_ratings(review_id);
CREATE INDEX IF NOT EXISTS idx_review_ratings_user_id ON review_ratings(user_id);

-- =====================================================
-- 9. ИНДЕКСЫ ДЛЯ РЕЖИССЁРОВ
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_directors_name ON directors(name);
CREATE INDEX IF NOT EXISTS idx_film_director_film_id ON film_director(film_id);
CREATE INDEX IF NOT EXISTS idx_film_director_director_id ON film_director(director_id);

-- =====================================================
-- 10. ИНДЕКСЫ ДЛЯ СОБЫТИЙ
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_events_user_id ON events(user_id);
CREATE INDEX IF NOT EXISTS idx_events_timestamp ON events(timestamp);
CREATE INDEX IF NOT EXISTS idx_events_user_timestamp ON events(user_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_events_entity ON events(entity_id);

-- =====================================================
-- 11. СБРОС АВТОИНКРЕМЕНТОВ ПРИ ЗАПУСКЕ
-- =====================================================

ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE films ALTER COLUMN id RESTART WITH 1;
ALTER TABLE directors ALTER COLUMN id RESTART WITH 1;
ALTER TABLE reviews ALTER COLUMN id RESTART WITH 1;
ALTER TABLE events ALTER COLUMN id RESTART WITH 1;

-- =====================================================
-- 12. ТРИГГЕР ДЛЯ АВТО-ОБНОВЛЕНИЯ updated_at В marks
-- =====================================================
-- ВРЕМЕННО ОТКЛЮЧЁН (требуется класс UpdateTimestampTrigger)
-- CREATE TRIGGER IF NOT EXISTS marks_updated_at
-- BEFORE UPDATE ON marks
-- FOR EACH ROW
-- CALL "ru.yandex.practicum.filmorate.util.UpdateTimestampTrigger";